package org.example.dao;

import org.example.pojo.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_order
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKey(Order record);
}