package org.example.dao;

import org.example.pojo.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKey(Product record);
}