package org.example.dao;

import org.example.pojo.ProductStock;

public interface ProductStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insert(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insertSelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    ProductStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKeySelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKey(ProductStock record);
}