package org.example.dao;

import org.example.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_miaosha_user
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    int updateByPrimaryKey(User record);
}