package org.example.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.order_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.amount
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.product_count
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.product_price
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_order.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.id
     *
     * @return the value of t_miaosha_order.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.id
     *
     * @param id the value for t_miaosha_order.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.order_id
     *
     * @return the value of t_miaosha_order.order_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.order_id
     *
     * @param orderId the value for t_miaosha_order.order_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.amount
     *
     * @return the value of t_miaosha_order.amount
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.amount
     *
     * @param amount the value for t_miaosha_order.amount
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.user_id
     *
     * @return the value of t_miaosha_order.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.user_id
     *
     * @param userId the value for t_miaosha_order.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.address
     *
     * @return the value of t_miaosha_order.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.address
     *
     * @param address the value for t_miaosha_order.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.product_id
     *
     * @return the value of t_miaosha_order.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.product_id
     *
     * @param productId the value for t_miaosha_order.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.product_count
     *
     * @return the value of t_miaosha_order.product_count
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.product_count
     *
     * @param productCount the value for t_miaosha_order.product_count
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.product_price
     *
     * @return the value of t_miaosha_order.product_price
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.product_price
     *
     * @param productPrice the value for t_miaosha_order.product_price
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.create_time
     *
     * @return the value of t_miaosha_order.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.create_time
     *
     * @param createTime the value for t_miaosha_order.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_order.update_time
     *
     * @return the value of t_miaosha_order.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_order.update_time
     *
     * @param updateTime the value for t_miaosha_order.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}