package org.example.pojo;

import java.util.Date;

public class ProductStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_product_stock.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_product_stock.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_product_stock.product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer productStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_product_stock.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_product_stock.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_product_stock.id
     *
     * @return the value of t_miaosha_product_stock.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_product_stock.id
     *
     * @param id the value for t_miaosha_product_stock.id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_product_stock.product_id
     *
     * @return the value of t_miaosha_product_stock.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_product_stock.product_id
     *
     * @param productId the value for t_miaosha_product_stock.product_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_product_stock.product_stock
     *
     * @return the value of t_miaosha_product_stock.product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getProductStock() {
        return productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_product_stock.product_stock
     *
     * @param productStock the value for t_miaosha_product_stock.product_stock
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setProductStock(Integer productStock) {
        this.productStock = productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_product_stock.create_time
     *
     * @return the value of t_miaosha_product_stock.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_product_stock.create_time
     *
     * @param createTime the value for t_miaosha_product_stock.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_product_stock.update_time
     *
     * @return the value of t_miaosha_product_stock.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_product_stock.update_time
     *
     * @param updateTime the value for t_miaosha_product_stock.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}