package org.example.pojo;

import java.util.Date;

public class User {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.user_name
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.password
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.phone
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_miaosha_user.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.user_id
     *
     * @return the value of t_miaosha_user.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.user_id
     *
     * @param userId the value for t_miaosha_user.user_id
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.user_name
     *
     * @return the value of t_miaosha_user.user_name
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.user_name
     *
     * @param userName the value for t_miaosha_user.user_name
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.password
     *
     * @return the value of t_miaosha_user.password
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.password
     *
     * @param password the value for t_miaosha_user.password
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.phone
     *
     * @return the value of t_miaosha_user.phone
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.phone
     *
     * @param phone the value for t_miaosha_user.phone
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.address
     *
     * @return the value of t_miaosha_user.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.address
     *
     * @param address the value for t_miaosha_user.address
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.create_time
     *
     * @return the value of t_miaosha_user.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.create_time
     *
     * @param createTime the value for t_miaosha_user.create_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_miaosha_user.update_time
     *
     * @return the value of t_miaosha_user.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_miaosha_user.update_time
     *
     * @param updateTime the value for t_miaosha_user.update_time
     *
     * @mbg.generated Tue Mar 30 22:46:27 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}